#!/bin/sh

FILE_ID=$1
NUM=$2
TOKEN=`cat box_token.json | jq -r '.access_token'`
HTTP_CODE=`curl -s https://api.box.com/2.0/files/$FILE_ID/versions -H "Authorization: Bearer ${TOKEN}" -w '%{http_code}\n' -o get_old_versions_response`
if [ $HTTP_CODE == 200 ] ; then
  NUM_VERSIONS=`cat get_old_versions_response | jq '.entries | map(select(.trashed_at==null)) | length'`
  while [ $NUM -lt $NUM_VERSIONS ] ; do
    cat get_file_versions_response | jq -r ".entries[$NUM].id"
    NUM=`expr $NUM + 1`
  done
  exit 0
fi
echo "Error in get_old_versions : http status code is $HTTP_CODE"
exit 2