#!/bin/sh

FILE_ID=$1
NUM=$2
TOKEN=`cat box_token.json | jq -r '.access_token'`
HTTP_CODE=`curl -s https://api.box.com/2.0/files/$FILE_ID/versions -H "Authorization: Bearer ${TOKEN}" -w '%{http_code}\n' -o manage_old_versions_response`
if [ $HTTP_CODE == 200 ] ; then
  NUM_VERSIONS=`cat manage_old_versions_response | jq '.entries | map(select(.trashed_at==null)) | length'`
  while [ $NUM -lt $NUM_VERSIONS ] ; do
    VERSION_ID=`cat manage_file_versions_response | jq -r ".entries[$NUM].id"`
    delete_version $FILE_ID $VERSION_ID
    if [ $? != 0 ] ; then
        exit 1
    fi
    NUM=`expr $NUM + 1`
  done
  exit 0
fi
cat manage_old_versions_response | jq '.'
echo "Error in manage_old_versions : http status code is $HTTP_CODE"
exit 2