#!/bin/sh

FILE_ID=$1
FILE_PATH=$2
echo "" > update_file_response
TOKEN=`cat box_token.json | jq -r '.access_token'`
HTTP_CODE=`curl -s https://upload.box.com/api/2.0/files/$FILE_ID/content -H "Authorization: Bearer ${TOKEN}" -X POST -F file=@$FILE_PATH -w '%{http_code}\n' -o update_file_response`
if [ $HTTP_CODE == 201 ] ; then
  echo "File $FILE_PATH successfully uploaded as new version of $FILE_ID"
  exit 0
fi
cat update_file_response | jq '.'
echo "Error in update_file : http status code is $HTTP_CODE"
exit 2